name: Validate JSON

on:
  push:
    paths:
      - 'static/blog/posts.json'
  pull_request:
    paths:
      - 'static/blog/posts.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate posts.json
        run: |
          cat static/blog/posts.json | python3 -m json.tool
